# Generated by Django 2.2.3 on 2019-07-06 16:09

from django.db import migrations, models
import djongo.models.fields
import seating.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', djongo.models.fields.EmbeddedModelField(model_container=seating.models.Seats, null=True)),
                ('service_date', models.DateField(db_index=True, max_length=255)),
            ],
        ),
    ]
